
server:
  port: 30000
spring:
  cloud:
    nacos:
      discovery:
        group: dev
        namespace: seckill
        server-addr: ${spring.cloud.nacos.server-addr}
    gateway:
      routes:
      - id: integrate_router
        uri: lb://integrate
        predicates:
        - Path=/api/integrate/**
        filters:
        - RewritePath=/api/integrate/?(?<segment>.*), /$\{segment}

      - id: commodity_router
        uri: lb://commodity
        predicates:
        - Path=/api/commodity/**
        filters:
        - RewritePath=/api/commodity/?(?<segment>.*), /$\{segment}

      - id: sys_router
        uri: lb://sys
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/?(?<segment>.*), /$\{segment}

